### ISSUE TITLE
Cooperation with syncthing-arubislander?

### ISSUE THREAD

**Issue by ppd** [GitHubForSnap/syncthing-gael#1]
Hi,

just a heads-up: syncthing-arubislander (https://gitlab.com/arubislander/syncthing-snap) has received a significant update very recently. It supports running as a root daemon and also running as a normal user (as is recommended for desktops). So if you see some overlap with your use-case, maybe we could collaborate on a common code base.

Cheers, ppd

**Comment by GitHubForSnap** [comment]
Hi,

Thank you for reaching out.

As I'm migrating all my servers (router, nas, backups, ....) to Ubuntu Core 20, I need snaps for everything. And syncthing is a key part of my architecture.
Three weeks ago when I started looking for a snap of syncthing I noticed Terence Sambo's snap but at the time it was 2 versions behind and had last been updated in December 2020 (I think).

I didn't bother contacting him (as I could/should have) and was like "Oh well let's see if I can build a snap myself".
It was quite easy and my snap was working very well but it was unlisted. No one could find it but me.
A few days later I made it public because it didn't make sense to keep it to myself. It's FOSS after all.

I never thought people would be interested in the snaps I develop/package for my personal use.
It was never my intend to uselessly fork or "steal" subscribers of Terence Sambo's snap.

As I'm really not interested in the Desktop side of syncthing and as it seems you're doing great things over there would you like me to redirect people to your snap?

Cheers

**Comment by ppd** [comment]
Fair enough. The outdated version was a bit annoying, so I did the same thing as you and developed my own (private) snap. Then I thought about the fact that motivation and manpower is a scarce resource and proposed the improvements to Terence's snap. I hope that it's going to be maintained better with more eyes on it in the future.

As for the desktop users: if you feel like it, you could drop a sentence into the description. That would be helpful for them to understand the key difference between both snaps.

**Comment by GitHubForSnap** [comment]
Done.
